import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "@emotion/styled";

import MainLayout from "@layouts/MainLayout";
import WithCover from "@layouts/WithCover";
import { Form, FieldsList } from "@modules/Form";
import { sendEmail } from "@api/Email";
import { useReCaptcha } from "@hooks/useReCaptcha";

const formFields: FieldsList = [
  {
    label: "Name",
    type: "text",
    value: "",
    parse: (value: string) => value.trim(),
  },
  {
    label: "Age",
    type: "number",
    value: 0,
    parse: (value: string) => Number(value),
  },
  {
    label: "Email",
    type: "email",
    value: "",
    parse: (value: string) => value.trim(),
  },
];

const ContactUs: NextPage = () => {
  const { verifyReCaptcha } = useReCaptcha();

  async function onSubmitForm(values: Record<string, unknown>) {
    // Instead of blocking user from submitting the form, we can tag
    // the email as spam for further review.
    const reCaptchaPassed = await verifyReCaptcha();
    const email = {
      title: `[spam: ${reCaptchaPassed}] Contact Us`,
      body: JSON.stringify(values),
    };
    console.log(email);
    await sendEmail(email);
  }

  return (
    <MainLayout>
      <Head>
        <title>Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithCover title="Contact us Page">
        <Container>
          <Form
            fieldsList={formFields}
            onSubmit={onSubmitForm}
            onSubmitMessage="Submit"
          />
        </Container>
      </WithCover>
    </MainLayout>
  );
};

export default ContactUs;

const Container = styled.div`
  display: flex;
  justify-content: center;
  min-width: 100%;
`;
